# Generated by Django 3.1.2 on 2020-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flash',
            name='description_kk',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='flash',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='flash',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='flash',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='flash',
            name='url_kk',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='flash',
            name='url_ru',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
    ]
