# Generated by Django 3.1.2 on 2020-10-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_privet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Privet',
        ),
        migrations.AddField(
            model_name='courses',
            name='hour',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кол-во часов'),
        ),
        migrations.AddField(
            model_name='courses_kaz',
            name='hour',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кол-во часов'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='courses_kaz',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
