# Generated by Django 3.1.2 on 2020-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201020_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.TextField(blank=True, max_length=120, verbose_name='Город')),
                ('iin', models.CharField(default='SOME STRING', max_length=15, verbose_name='Телефон')),
                ('course', models.CharField(blank=True, max_length=150, verbose_name='Курс')),
                ('status', models.CharField(blank=True, choices=[('buy', 'Оплатил'), ('hold', 'Не оплатил')], default='hold', max_length=100, verbose_name='Статус покупки')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
