# Generated by Django 3.1.2 on 2020-10-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='city',
        ),
    ]
