# Generated by Django 3.1.2 on 2020-10-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_reviews_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description_kz',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_kz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
