# Generated by Django 3.1.2 on 2020-10-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201026_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='name_kz',
            new_name='name_kk',
        ),
    ]
