# Generated by Django 3.1.2 on 2020-10-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201026_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='courses',
            name='url_kk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='courses',
            name='url_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
    ]
