# Generated by Django 3.1.2 on 2020-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201029_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='url_kk',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='url_ru',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка'),
        ),
    ]
