# Generated by Django 3.1.2 on 2020-11-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201029_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses_kaz',
        ),
    ]
