# Generated by Django 3.1.2 on 2020-10-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Content',
        ),
    ]
