# Generated by Django 3.1.2 on 2020-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccg', '0002_auto_20201017_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('buy', 'Оплатил'), ('hold', 'Не оплатил')], default='hold', max_length=100, verbose_name='Статус покупки'),
        ),
    ]
