# Generated by Django 3.1.2 on 2020-10-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccg', '0003_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='course',
            field=models.CharField(blank=True, max_length=150, verbose_name='Курс'),
        ),
    ]
